<?php
session_start();
/* Name: Ashraf Mirza & Andrew Sicard-Woodall
  class: INT525A test
  Final Project - Movie Collection
*/
if(!isset($_SESSION[userid])) {
  $redirect="yes";
  header( "refresh:5;url=index.phtml" );
  $redirectmsg="You are not logged in, you are being redirected to the login page. If you are not redirected click on Home above.";
}
?>
<?php
/* MySQL connection */
include 'dbclass.phtml';

					
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php $_SESSION[uname] ?> - Movie Collection</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="English" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="stylesheet" type="text/css" href="/css/tmdb.css" media="screen" />
</head>
<?php
$db = new Database;
$sql = "SELECT background FROM movf ORDER BY RAND() LIMIT 1";
$res= $db->query($sql);
if($res)
{
while($row=$res->fetch_object()) {
$bg=$row->background;
}
}

if ($bg) { echo '<body style="background:#FFFFFF url('.$bg.') repeat-y fixed top center; font-family: Verdana, Tahoma, Arial, sans-serif; width: 100%; font-size: 12px; padding: 0; margin: 0; color: #FFF5EE; line-height: 20px;" >';
}
else {
echo "<body>";
}
?>
<div id="wrap">
<div id="headerbg">
<div id="header">
<h1><a href="/movie.html">Movie Collection</a></h1>

</div>
</div>
<div id="menu">
<ul>
    <li><a href="index.phtml">Home</a></li>
	<li><a href="logout.phtml">Logout</a></li>
	<li><a href="addmovie.phtml">Add Movie</a></li>
<!-- Add Menu Items here if needed -->
</ul>
</div>

<div id="content">
<!-- Left Navigation -->
<div id="left">
<h2>Links: </h2>
<div class="box">
<ul>
<li><a href="movie.phtml">Your Collection</a></li>  
<li><a href="addmovie.phtml">Add a Movie</a></li>  
</ul>
</div>
</div>

	
<div id="right">
<h2>Your Movies</h2>
<?php
if(isset($_GET[page])) $page=$_GET['page'];
if(!isset($_SESSION[userid])) {
echo "<span id=\"activmsg\">".$redirectmsg."</span>";
}
else 
	{
	   if(isset($_GET[sort])) {
            $sql = "SELECT movf.*, ".$_SESSION[uname]."movies.* FROM movf, ".$_SESSION[uname]."movies WHERE ".$_SESSION[uname]."movies.movieid = movf.movieid ORDER BY movf.".$_GET[sort]." ASC";
            }
            	else $sql = "SELECT movf.*, ".$_SESSION[uname]."movies.* FROM movf, ".$_SESSION[uname]."movies WHERE ".$_SESSION[uname]."movies.movieid = movf.movieid ORDER BY movf.moviename ASC";
           
	
    $res= $db->query($sql);
	echo "<span id=activmsg>You have <strong>". $db->numrows($res) ." movies</strong> in your collection. Please view them below.</span><br /><br />";
    echo "<span id=activmsg><a href=movie.phtml>Table View</a></span><br /><br />";
   
    
    $num = $db->numrows($res);
	#echo $mysqli->error; // debugging
	include 'paginate.phtml';
    echo $pagination;
    $sql = $sql." LIMIT $start,$limit";
    $res= $db->query($sql);
    if($num>0)
	{	
		while ($newArray = $db->fetch_array($res)) {
						//calculate result # based on page # limit and count each result on page and set vars from associative array
						$fnum = ((($page * $limit) - $limit) + ($count + 1));
						$movid = $newArray['movieid'];
						$movname = $newArray['moviename'];
						$reldate = $newArray['releasedate'];
						$plot = $newArray['plot'];
						$trailer = $newArray['trailer'];
						$rating = $newArray['rating'];
						$genre = $newArray['genre'];
						$imdbid = $newArray['imdb_id'];
						$studio = $newArray['studio'];
						$poster = $newArray['poster'];
						$background = $newArray['background'];
						$useridmovieadded = $newArray['useridmovieadded'];
						$favstatus = $newArray['favstatus'];
						$loanstatus = $newArray['loanstatus'];
						$dateadded = $newArray['dateadded'];
						?>
						<div id="enclosmov">
						<?php
						echo "<h2>";
						echo $movname;
						#echo $mysqli->error;
						echo "</h2>";

						echo "<div id=\"rightimg\"><a href=viewmovies.phtml?movid=".$movid."><img src=\"" . $poster . "\"alt=\"" . $movname . "\" /></a></div>";
						?>
						<div id="movoutcontainer">
						<div id="movdetails">
						<?php
						if (!empty($imdbid)) {
						echo "<p class=\"movdetailsf\"><a href=http://www.imdb.com/title/" . $imdbid . " target=\"_blank\"> IMDB PAGE </a>";
						}
						echo "<br />";
						echo "<p class=\"movdetailsf\"><a href=http://www.themoviedb.org/movie/" . $movid . " target=\"_blank\"> tmDB PAGE </a>";
						echo "<br />";
						if (!empty($trailer)) {
						echo "<a href=" . $trailer . " target=\"_blank\"> Trailer </a>";
						echo "<br />";
						}
							$sql2="SELECT name FROM moviecrew WHERE movieid=".$movid." AND job='Director'";
							$res2=$db->query($sql2);
							while ($newArray2 = $db->fetch_array($res2)) {
							$dirname=$newArray2['name'];
							echo "Directed by: <strong>".$dirname."</strong>";
							}
						echo "<br />";
						if (!empty($reldate)) echo "Release Date: " . $reldate . "";
						else echo "Release Date: Not Available";
						echo "<br />";
						
						echo "Rating: " . $rating . "";
						echo "<br />";
						
						echo "<br /><strong>Plot overview:</strong> <br />";
							if (!empty($plot)){
							echo $plot ."<br /><br />";
							}
							else echo "Not Available <br /><br />";
						
						?>
						</div>
						</div>
						</div>
						<?php
						
						
						
					}
        echo $pagination;
	}
	
}	
?>

<div id="footer">
<br />
<?php
include 'footer.phtml';
?>

</div> <!--closing footer -->
</div> <!-- closing right -->


</div> <!-- closing content -->



</div> <!-- closing wrap -->

</body>


</html>