<?php
//paginate include

$limit=10;
			/*  If page is set the first row to display on the page should be page # - 1 X limit, 
				which gives us the first result that should be displayed on the page 
				if not then set startrow and page to 0
			*/
            $adjacents=2;
			if($page)
				$start = ($page - 1) * $limit;
			else{
				$start = 0;
				$page = 0;
				}

			/* if page # is 0 set page to 1 */
			if ($page==0){$page = 1;}
			// set $ prev and $ next vars and 2nd last page var to facilitate pagination
			$prev = $page - 1;
			$next = $page + 1;
			// calculate which page # will be the last page
			$lastpage = ceil($num/$limit);
			//calculate 2nd last page for pagination.
			$lastpager = $lastpage - 1;
            if(isset($_GET[sort])) $sort = "&sort=".$_GET[sort]."";
			// set pagination field to blank when starting
			$pagination = "";
            $pagination.= "<div class=\"pagination\">";
			//if the resultset requires more than one page perform pagination and return results
			if($lastpage > 1)
			{
				
				//prev button
				if ($page > 1)
					$pagination.= "<span><a href=\"".$_SERVER[PHP_SELF]."?page=$prev".$sort."\"><< prev</a></span>";
				else
					$pagination.= "<span class=\"disabled\"><< prev</span>";
					
				//pagination set up based on # of pages
				if ($lastpage < 7 + ($adjacents * 2))  //if page #s are too low do not bother breaking it up
				{
					for ($counter = 1; $counter <= $lastpage; $counter++) //page counter to display page links
					{
						if ($counter==$page) //if on current page disable link
							$pagination.= "<span class=\"current\">$counter</span>";
						else //enable page links
							$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=$counter".$sort."\">$counter</a>";
					}
				}
				elseif($lastpage > 5 + ($adjacents * 2)) // hide extraneous pages
				{
					//If close to starting page, only hide later pages
					if ($page < 1 + ($adjacents * 2))
					{
						for ($counter = 1; $counter < 4 + ($adjacents * 2); $counter++)
						{
							if ($counter == $page)
								$pagination.= "<span class=\"current\">$counter</span>";
							else
								$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=$counter".$sort."\">$counter</a>";
						}
						$pagination.= "...";
						$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=$lastpager".$sort."\">$lastpager</a>";
						$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=$lastpage".$sort."\">$lastpage</a>";
					}
					//in middle, hide some front and back
					elseif($lastpage - ($adjacents * 2) > $page && $page > ($adjacents * 2))
					{
						$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=1".$sort."\">1</a>";
						$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=2".$sort."\">2</a>";
						$pagination.= "...";
						for ($counter = $page - $adjacents; $counter <= $page + $adjacents; $counter++)
						{
							if ($counter == $page)
								$pagination.= "<span class=\"current\">$counter</span>";
							else
								$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=$counter".$sort."\">$counter</a>";
						}
						$pagination.= "...";
						$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=$lastpager".$sort."\">$lastpager</a>";
						$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=$lastpage".$sort."\">$lastpage</a>";
					}
					//close to end; only hide early pages
					else
					{
						$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=1".$sort."\">1</a>";
						$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=2".$sort."\">2</a>";
						$pagination.= "...";
						for ($counter = $lastpage - (2 + ($adjacents * 2)); $counter <= $lastpage; $counter++)
						{
							if ($counter == $page)
								$pagination.= "<span class=\"current\">$counter</span>";
							else
								$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=$counter".$sort."\">$counter</a>";
						}
					}
				}
        }
        if ($page < $counter - 1){
					$pagination.= "<a href=\"".$_SERVER[PHP_SELF]."?page=$next".$sort."\">next >></a></div>";
                    }
				else
                {
					$pagination.= "<span class=\"disabled\">next >></span></div>";
				}
            
?>