<?php
session_start();
/* Name: Ashraf Mirza
  Student #: 033 306 051
  class: PHP701 A
  Final Project - Movie Collection
*/
//registration page
?>
<?php
/* MySQL connection */
include 'dbclass.phtml';
$db = new Database;	
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Register - Movie Collection</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="English" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="stylesheet" type="text/css" href="/css/tmdb.css" media="screen" />
</head>
<?php
$sql = "SELECT background FROM movf ORDER BY RAND() LIMIT 1";
$res= $db->query($sql);
if($res)
{
while($row=$res->fetch_object()) {
$bg=$row->background;
}
}

if ($bg) { echo '<body style="background:#FFFFFF url('.$bg.') repeat-y fixed top center; font-family: Verdana, Tahoma, Arial, sans-serif; width: 100%; font-size: 12px; padding: 0; margin: 0; color: #FFF5EE; line-height: 20px;" >';
}
else {
echo "<body>";
}
?>
<div id="wrap">
<div id="headerbg">
<div id="header">
<h1><a href="index.phtml">Movie Collection</a></h1>

</div>
</div>
<div id="menu">
<ul>
    <li><a href="index.phtml">Home</a></li>
<!-- Add Menu Items here if needed -->
</ul>
</div>

<div id="content">
<!-- Left Navigation -->
<div id="left">
<h2>Categories: </h2>
<div class="box">
<ul>
<li><a href="#">Testing</a></li>  
</ul>
</div>
</div>

<?php
$errorcount=0;
	if(isset($_POST[submit])) {
		if(trim($_POST[username])=='' || strlen(trim($_POST[username])) <6 || strlen(trim($_POST[username])) >12) {
			$usernameerror="Username must be between 6 and 12 characters. <br />";
			$errorcount++;
		}
		else {
		$sql= "SELECT username FROM there WHERE username = '".$_POST[username]."'";
		$res = $db->query($sql);
		}
		if ($res) {
			$nofrows = $db->numrows($res);
		}
		if($nofrows=="1") {
			$usernameerror="That username is already taken, please choose another username. <br />";
			$errorcount++;
		}
		
		if(trim($_POST[password])=='' || strlen(trim($_POST[password])) <6) {
			$passwderror="Your password must be at least 6 characters long. <br />";
			$errorcount++;
		}
		elseif(!ereg("^[A-Za-z0-9_!@#$%^*]{6,12}$", trim($_POST[password]))) {
			$passwderror="Your password must be 6-12 least 6 characters long, you have some some incompatible text in your password Please only use Letters, numbers and the following special characters \"!@#$%^&*\". <br />";
			$errorcount++;
		}
		if(trim($_POST[password])!=trim($_POST[confpassword])) {
			$cpasswderror="The two passwords do not match <br />";
			$errorcount++;
		}
		if(!ereg("^[A-Z]{1}[A-Za-z']{1,15}$", trim($_POST[fname]))) {
			$fnameerror="First name has to be between 2 and 15 letters and the first letter has to be capitalized. <br />"; 
			$errorcount++;
		}
		if(!ereg("^[A-Z]{1}[A-Za-z']{1,15}$", trim($_POST[lname]))) {
			$lnameerror="Last name has to be between 2 and 15 letters and the first letter has to be capitalized. <br />";
			$errorcount++;
		}
		if(trim($_POST[email])==''){
			$emailerror="Please enter an email address in the email address field. <br />";
			$errorcount++;
		}
		else {
			if(!eregi("^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-99]+)*(\.[a-z]{2,3})$", $_POST[email])) {
				$emailerror="The email address you entered is not in the proper format. The format should be username@domain.com. <br />";
				$errorcount++;
			}	
		}
		
		if(!ereg("^[0-9]{2}$", $_POST[dob_month])) {
			$dob_month_error="Please choose the month of your birth. ";
			$errorcount++;
		}
		
		if(!ereg("^[0-9]{2}$", $_POST[dob_day])) {
			$dob_day_error="Please choose the day of your birth. ";
			$errorcount++;
		}
		
		if(!ereg("^[0-9]{4}$", $_POST[dob_year])) {
			$dob_year_error="Please choose the year of your birth. ";
			$errorcount++;
		}
		
	}
	
	?>

	
<div id="right">
<?php if(!isset($_POST[submit]) || ($errorcount>0)) {
echo "<h2>Registration Form</h2>";
}
elseif(isset($_POST[submit]) && ($errorcount=="0")) {
echo "<h2>Account Activation</h2>";
} ?>
<br /><br />
<?php if(!isset($_POST[submit]) || ($errorcount>0)) {
?>	
<form id="form" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
	<fieldset>
		<legend>Register Here</legend>
			
			<span id="errormsg"> * All Fields are required </span>
			<br /> <br /> <br />
			<label for="username">Username:</label>
			<input type="text" name="username" id="username" value="<?php $_POST[username] ?>"/> <?php "<span id=\"errormsg\">" . $usernameerror ."</span>" ?>
			<br />
			
			<label for="password">Password:</label>
			<input type="password" name="password" id="password" value="<?php $_POST[password] ?>"/> <?php "<span id=\"errormsg\">" . $passwderror ."</span>" ?>
			<br />
			
			<label for="confpassword">Confirm Password:</label>
			<input type="password" name="confpassword" id="confpassword" value="<?php $_POST[confpassword] ?>"/> <?php "<span id=\"errormsg\">" . $cpasswderror ."</span>" ?>
			<br />
			<br />
			<br />
			
			<label for="fname">First Name:</label> 
			<input type="text" name="fname" id="fname" value="<?php $_POST[fname] ?>"/> <?php "<span id=\"errormsg\">" .$fnameerror ."</span>" ?>
			<br />

			<label for="lname">Last Name:</label>
			<input type="text" name="lname" id="lname" value="<?php $_POST[lname] ?>"/> <?php "<span id=\"errormsg\">" .$lnameerror ."</span>" ?>
			<br />
			
			<label for="email">E-mail Address:</label> 
			<input type="text" name="email" id="email" value="<?php $_POST[email] ?>"/> <?php "<span id=\"errormsg\">" .$emailerror ."</span>" ?>
			<br />
			
			<br />
			<br />
			<br />
			
			<?php
			include 'dob.phtml';
			?>
			
			
			<?php if($errorcount>0) echo "<span id=\"errormsg\"> There are ".$errorcount." errors in the form please fix them before you can proceed. </span> <br />";?>
			<label for="submit"></label>
			<input type="submit" name="submit" value="Submit" class="button">
		</fieldset>
	</form>
<?php
}
?>
<?php
	if(isset($_POST[submit]) && ($errorcount=="0")) {
		//set user input to hard vars
		$uname=trim($_POST[username]);
		$passwd=trim($_POST[password]);
		$passwd=md5($passwd);
		$fname=trim($_POST[fname]);
		$lname=trim($_POST[lname]);
		$email=trim($_POST[email]);
		$dob=$_POST[dob_year]."-".$_POST[dob_month]."-".$_POST[dob_day];
		

				$sql="SELECT birth_date FROM there WHERE username='".$uname."'";
				$res = $db->query($sql);
				if ($res) {
					while ($newArray = $db->fetch_array($res)) {
						$bday= $newArray['birth_date'];
						
					}
				}
				$activecode=md5($uname.$bday);
				$hash=md5($email);
	
				require_once('phpmailer/class.phpmailer.php');
				$mail             = new PHPMailer();
	
				$mail->IsSMTP(); // telling the class to use SMTP
				$mail->Host       = "smtp.gmail.com"; // SMTP server
				//$mail->SMTPDebug  = 2;                     // enables SMTP debug information (for testing)
														   // 1 = errors and messages
														   // 2 = messages only
				$mail->SMTPAuth   = true;                  // enable SMTP authentication
				$mail->SMTPSecure = "ssl";                 // sets the prefix to the servier
				$mail->Host       = "smtp.gmail.com";      // sets GMAIL as the SMTP server
				$mail->Port       = 465;                   // set the SMTP port for the GMAIL server
				$mail->Username   = "movcoll@gmail.com";  // GMAIL username
				$mail->Password   = "jamesbond";            // GMAIL password

				$mail->SetFrom('movcoll@gmail.com', 'Movie Collection');

				$mail->AddReplyTo("movcoll@gmail.com","Movie Collection");

				$mail->Subject    = "Hello $fname $lname, please activate your Movie Collection account!";
				$body = "Hello $fname $lname,<br />You have been registered and need to activate your account. Click the link below or paste it into the URL bar of your browser<br /><a href=http://".$_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"]."/phtml/tmdb/activate.phtml?activate=".$activecode."&hash=".$hash.">http://".$_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"]."/phtml/tmdb/activate.phtml?activate=".$activecode."&hash=".$hash."</a><br />Thanks!";
				//$mail->AltBody    = "To view the message, please use an HTML compatible email viewer!"; // optional, comment out and test

				$mail->MsgHTML($body);

				$address = $email;
				$mail->AddAddress($address, $uname);

				//$mail->AddAttachment("images/phpmailer.gif");      // attachment
				//$mail->AddAttachment("images/phpmailer_mini.gif"); // attachment

				if(!$mail->Send()) {
				  echo "Mailer Error: " . $mail->ErrorInfo;
				  echo "<span id=\"activmsg\">Could not sign you up at this time please try again later.</span>";
				} 
				 { 
						//echo "Message sent!";
						$sql= "INSERT there (username, passwd, activate_status, first_name, last_name, birth_date, email, activecode, emailhash) VALUES ('".$uname."', '".$passwd."', '0', '".$fname."', '".$lname."', '".$dob."', '".$email."', '".$activecode."', '".$hash."' )";
						$res=$db->query($sql);
						if ($res===TRUE) {
						$sql = "CREATE TABLE `movies`.`".$uname."movies` (`useridmovieadded` SMALLINT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, `movieid` SMALLINT(11) NOT NULL, `favstatus` TINYINT(1) NOT NULL, `dateadded` DATE NOT NULL, `loanstatus` VARCHAR(200) NOT NULL) ENGINE = MyISAM";
						$res=$db->query($sql);
							if ($res===TRUE) {
							echo "<span id=\"activmsg\">Congratulations your account has been created, we have sent an email to your email at <strong>" . $_POST[email] . "</strong> with further instructions on your account</span> <br /> <br />";
							}
							else {
							echo "<span id=\"activmsg\">Could not sign you up at this time please try again later.</span>";
							printf("Could not insert record: %s\nPlease try again later\n", mysqli_error($mysqli));
							}
						}
						else {
							echo "<span id=\"activmsg\">Could not sign you up at this time please try again later.</span>";
							printf("Could not insert record: %s\nPlease try again later\n", mysqli_error($mysqli));
						}
				}

				
				
	}
?>
<div id="footer">			
<br />
<?php
include 'footer.phtml';
?>

</div> <!--closing footer -->
</div> <!-- closing right -->


</div> <!-- closing content -->



</div> <!-- closing wrap -->

</body>

</html>